format = """
$directory\
$git_branch\
$git_status\
$fill\
$lua\
$python\
$nodejs\
$aws\
$docker_context\
$line_break\
$character"""

[fill]
symbol = ' '

[directory]
style = "bold #7BA546" 
format = "[$path ]($style)"
truncation_length = 3
fish_style_pwd_dir_length = 1

[character]
success_symbol = "[❯](bold #A1C85A)"

[git_branch]
symbol = " "
style = "bold #467A4D"

[git_status]
style = "bold #699663"

[time]
disabled = false
time_format = "%H:%M"
style = "dimmed #2E5232"
format = "[ $time]($style)"

[python]
symbol = " "
style = "bold #5B8464"
format = '[$symbol$version ]($style)'
detect_extensions = []

[nodejs]
symbol = " "
style = "bold #4A7A50"
format = '[$symbol$version ]($style)'

[lua]
symbol = " "
style = "bold #73A883"
format = '[$symbol$version ]($style)'
