shell fish

# Schriftart (Stelle sicher, dass JetBrains Mono installiert ist)
font_family      MesloLGS Nerd Font Mono
font_size        11.0

# Transparenz
background_opacity 0.8
# (Optional) Blur für den Hintergrund - das musst du in der hyprland.conf machen!

# Fenster-Abstände (damit der Text nicht am Rand klebt)
window_padding_width 15

# Farben (One Dark / Tokyo Night Style)
foreground #a9b1d6
background #1a1b26

# Cursor
cursor #c0caf5
cursor_shape beam

mouse_hide_wait -3.0
hide_window_decorations yes
cursor_trail 1
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2
cursor_blink_interval -1 
cursor_stop_blinking_after 15.0

tab_bar_style powerline
tab_powerline_style slanted

include ~/.cache/wal/colors-kitty.conf
